testname: webMUSHRA Decoder Listening Test
testId: Ambisonic_Decoder_Test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: >
        Welcome to the Ambisonic Decoder Listening Test part 2<br/>
        This test is based on recorded tracks and more environmental and listener-based characteristics <br/>
        Once the test is finished, please fill out the questinonnaire and submit. <br/>
        You may take a break or pull out from doing the test at any time you like. <br/>
        Thank you! <br/>
        
    - type: generic
      id: Instructions
      name: Instructions
      content: > 
        This is the second half of the test. This half will test the following characteristics; <br/>
        Source Distance, Ensemble Width, Listener Envelopment, Timbre <br/> <br/>
        For each characteristic there will be an available reference on the left hand side of the page which you can listen to at any time. <br/>
        There will be a number of audio files for you to listen to which must be rated from 0-100 using the associated sliders. <br/>
        This rating should be based on how similar the selected audio file is to the reference file for the given characteristic. <br/>
        A rating of 0 would describe the chosen file as pure noise and a rating of 100 would state the file has no difference to the available reference. <br/> <br/>
        Please ensure to compare the selected track against the REFERENCE ONLY and not to the other audio files. <br/> <br/>
        There are also two sliders under the waveform of the audio file. <br/>
        These can be dragged at any time to listen to the selected range of the audio on loop <br/>
        
        
    # - type: mushra
      # id: DistCinDrums
      # name: TEST 1 - SOURCE DISTANCE
      # content: Please rate the test files from 0-100 on how similar the distance of the sound source of the track is to the available reference.
      # showWaveform: true
      # enableLooping: true
      # reference: configs/resources/audio/Test1/T1-Drums-45deg-4m-Huddersfield-KU100.wav
      # createAnchor35: false
      # createAnchor70: false
      # stimuli:
          # C1: configs/resources/audio/Test1/T1-Drums-7.1.4-Anchor.wav
          # C2: configs/resources/audio/Test1/T1-Drums-AllRAD-7.1.4.wav
          # C3: configs/resources/audio/Test1/T1-Drums-DTS-7.1.4.wav
          # C4: configs/resources/audio/Test1/T1-Drums-Harpex-7.1.4.wav
    - type: mushra
      id: distCinVoice
      name: TEST 2 - SOURCE DISTANCE
      content: Please rate the test files from 0-100 on how similar the distance of the sound source of the track is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test2/T2-Speech-45deg-4m-Huddersfield-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test2/T2-Speech-DTS-7.1.4.wav
          C2: configs/resources/audio/Test2/T2-Speech-7.1.4-Anchor.wav
          C3: configs/resources/audio/Test2/T2-Speech-Harpex-7.1.4.wav
          C4: configs/resources/audio/Test2/T2-Speech-AllRAD-7.1.4.wav
    - type: mushra
      id: distCubeDrums
      name: TEST 3 - SOURCE DISTANCE
      content: Please rate the test files from 0-100 on how similar the distance of the sound source of the track is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test3/T3-Drums-330deg-3m-Huddersfield-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test3/T3-Drums-AllRad-Cube.wav
          C2: configs/resources/audio/Test3/T3-Drums-Harpex-Cube.wav
          C3: configs/resources/audio/Test3/T3-Drums-DTS-Cube.wav
          C4: configs/resources/audio/Test3/T3-Drums-Cube-Anchor.wav
    - type: mushra
      id: distCubeVoice
      name: TEST 4 - SOURCE DISTANCE
      content: Please rate the test files from 0-100 on how similar the distance of the sound source of the track is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test4/T4-Speech-330deg-3m-Huddersfield-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test4/T4-Speech-DTS-Cube.wav
          C2: configs/resources/audio/Test4/T4-Speech-Cube-Anchor.wav
          C3: configs/resources/audio/Test4/T4-Speech-Harpex-Cube.wav
          C4: configs/resources/audio/Test4/T4-Speech-AllRad-Cube.wav
    - type: mushra
      id: CinEnsemble
      name: TEST 5 - ENSEMBLE WIDTH
      content: Please rate the test files from 0-100 on how similar the width of the ensemble is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test5/T5-Ensemble-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test5/T5-Ensemble-DTS-7.1.4.wav
          C2: configs/resources/audio/Test5/T5-Ensemble-Harpex-7.1.4.wav
          C3: configs/resources/audio/Test5/T5-Ensemble-AllRad-7.1.4.wav
          C4: configs/resources/audio/Test5/T5-Ensemble-Anchor-7.1.4.wav
    - type: mushra
      id: CubeEnsemble
      name: TEST 6 - ENSEMBLE WIDTH
      content: Please rate the test files from 0-100 on how similar the width of the ensemble is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test6/T6-Ensemble-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test6/T6-Ensemble-Harpex-Cube.wav
          C2: configs/resources/audio/Test6/T6-Ensemble-Anchor.wav
          C3: configs/resources/audio/Test6/T6-Ensemble-DTS-Cube.wav
          C4: configs/resources/audio/Test6/T6-Ensemble-AllRad-Cube.wav
    - type: mushra
      id: CinEnv
      name: TEST 7 - SPATIAL IMPRESSION, ENVELOPMENT
      content: Please rate the test files from 0-100 on how similar the envelopment of the sound scene is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test7/T7-Trio-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test7/T7-Trio-AllRad-7.1.4.wav
          C2: configs/resources/audio/Test7/T7-Trio-DTS-7.1.4.wav
          C3: configs/resources/audio/Test7/T7-Trio-Harpex-7.1.4.wav
          C4: configs/resources/audio/Test7/T7-Trio-Anchor.wav
    - type: mushra
      id: CubeEnv
      name: TEST 8 - SPATIAL IMPRESSION, ENVELOPMENT
      content: Please rate the test files from 0-100 on how similar the envelopment of the sound scene is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test8/T8-Trio-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test8/T8-Trio-Harpex-Cube.wav
          C2: configs/resources/audio/Test8/T8-Trio-AllRad-Cube.wav
          C3: configs/resources/audio/Test8/T8-Trio-Anchor.wav
          C4: configs/resources/audio/Test8/T8-Trio-DTS-Cube.wav
    - type: mushra
      id: CinTimbre
      name: TEST 9 - TIMBRE
      content: Please rate the test files from 0-100 on how similar the timbre of the selected track is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test9/T9-Piano-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test9/T9-Piano-Anchor.wav
          C2: configs/resources/audio/Test9/T9-Piano-AllRad-7.1.4.wav
          C3: configs/resources/audio/Test9/T9-Piano-Harpex-7.1.4.wav
          C4: configs/resources/audio/Test9/T9-Piano-DTS-7.1.4.wav
    - type: mushra
      id: CubeTimbre
      name: TEST 10 - TIMBRE
      content: Please rate the test files from 0-100 on how similar the timbre of the selected track is to the available reference.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/Test10/T10-Piano-KU100.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/Test10/T10-Piano-AllRad-Cube.wav
          C2: configs/resources/audio/Test10/T10-Piano-Harpex-Cube.wav
          C3: configs/resources/audio/Test10/T10-Piano-DTS-Cube.wav
          C4: configs/resources/audio/Test10/T10-Piano-Anchor.wav
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: false
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 20
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
          - type: likert
            name: experience
            label: Listening Test Experience
            response:
             - value: none
               label: None
             - value: little
               label: Little (1 or 2 previous tests)
             - value: extensive
               label: Considerable (Many Tests, Trained Listener)
          - type: likert
            name: detail
            label: Do you work with Audio professionally? If so, for how long?
            response: 
             - value: none
               label: 0 years
             - value: little
               label: 1-3 years
             - value: intermed
               label: 3-5 years
             - value: extensive
               label: 5+ years     
    